### ISSUE TITLE
Pruning old branches

### ISSUE THREAD

**Issue by dotwaffle** [earwig/git-repo-updater#18]
Quite often I'm in a situation where people create a lot of branches in the main repo and open a pull-request. Later on, those branches get deleted.

At the moment, I have to do "git remote update --prune" every time the number of branches no longer on the remote but not tracked locally gets out of hand. Is there any scope to add this into a normal "gitup" run too?

**Comment by earwig** [comment]
It looks like there's a configuration option you can set in git to get this behavior by default: https://github.com/git/git/commit/737c5a9cde708d6995c765b7c2e95033edd0a896.

Either way, sounds like a good idea to add it here too. I added a `--prune`/`-p` flag to get this behavior.

**Comment by dotwaffle** [comment]
Much obliged!
