### ISSUE TITLE
Bookmarks doesn't work on windows with python2

### ISSUE THREAD

**Issue by abhi92** [earwig/git-repo-updater#21]
Hi !  Thanks for this nice tool. Mostly works fine but only issue I have is that bookmarks doesn't work on windows with python2. When I add a path, it gets added to the config.ini file but when I run gitup, it just exits with **Error: C doesn't exist**
The issue seems to be with python2 configparser treating colons as delimiters. I did a `pip install configparser` (it installed v3.3.0r2) and it works fine now.
Maybe add it to  setup.py?

**Comment by abhi92** [comment]
Once this is pulled in, b71e6f4 can be reverted

**Comment by earwig** [comment]
We really shouldn't be using `.ini` to store bookmarks; it's not necessary and the type of data we need to store is very simple.

I might replace it with JSON or just a simple line-by-line list. This would fix this and the other weird configparser quirks.
