### ISSUE TITLE
status - feature request

### ISSUE THREAD

**Issue by michaelelrom** [earwig/git-repo-updater#23]
Hello,

First off, I really enjoy using the tool.  Quite a time saver!  Can you add a feature for a recursive git status command to check that I don't have any outstanding changes that need to be pushed up?

Thanks,

Mike

**Comment by earwig** [comment]
I'm a bit concerned about feature bloat if we start trying to implement too many features beyond simple updating (the next obvious suggestion would be recursive push, etc). [This StackOverflow question](http://stackoverflow.com/questions/816619/managing-many-git-repositories) has a lot of suggestions for alternate (more complex) repository management software, which might be more useful in your case.

I recognize the advantage of the bookmarking/recursive-traversal system that gitup sorta allows for, so I'm comfortable adding is a "custom" batch command option.

Something like `gitup --custom 'git status'`, which'll run that command on all of your repositories.

**Comment by earwig** [comment]
Implemented as described in 70e96ad.

**Comment by michaelelrom** [comment]
That makes sense, thanks!
