### ISSUE TITLE
Gitup doesn't work with path containing colon

### ISSUE THREAD

**Issue by slnovak** [earwig/git-repo-updater#28]
Hi,

This tool is great!

I'm currently using [`ghq`](https://github.com/motemen/ghq) to manage remote repositories. One of the repositories I have connects to Gitlab over HTTPs on a non-standard port (i.e., 4545) and thus I have a repository location of `/Users/me/dev/src/path.to.server:4545/project/repo`.

When adding this repository to `gitup`, I can verify that `.config/gitup/config.ini` has the line:

```
/Users/me/dev/src/path.to.server:4545/project/repo = repo
```

When Gitup attempts to update this repository, I get:

```
Error: /Users/me/dev/src/path.to.server doesn't exist!
```

Apparently the default delimiters that `configparser` use are both `=` and `:`, but can be changed. Can we look into [configuring](https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour) `configparser` to not use colons as a delimiter?

Thanks!

**Comment by earwig** [comment]
We've already fixed this, but you need to use the version on `develop` at the moment. I'll make a formal release later.
