### ISSUE TITLE
Feature Request: Support glob patterns in bookmarks

### ISSUE THREAD

**Issue by dominicbarnes** [earwig/git-repo-updater#29]
Currently, I can't simply put `~/Github/*` in my "bookmarks" file. Since I can pass that as an argument to `gitup`, it seems reasonable it should be supported there too. I fully understand that the shell actually expands those globs, rather than the `gitup` command, but even still I think it would be useful.

**Comment by earwig** [comment]
This is reasonable. I'll get on it.

**Comment by dominicbarnes** [comment]
Along the same lines, it seems that other patterns like `~` are not supported, and instead the canonical/absolute path is always required. This makes it tricky to share the bookmarks file across different platforms, as well as make manual management more tedious.

I _think_ by allowing for glob patterns may inherently allow for this too.
