### ISSUE TITLE
Tip: git already has the main feature

### ISSUE THREAD

**Issue by guyzmo** [earwig/git-repo-updater#36]
Hello,

in case you did not know, your main use case for this script is already being taken care by git itself. You can setup a remote that really has several URLs:

``` bash
# to set up a remote called "all" that will get updated with four URLs:
git remote add all URL1
git remote set-url all --add URL2
git remote set-url all --add URL3
git remote set-url all --add URL4
```

it's also a good idea to setup indepedently the remotes for each URL:

``` bash
git remote add repo1 URL1
git remote add repo2 URL2
git remote add repo3 URL3
git remote add repo4 URL4
```

And then you can push to all the URLs by pushing to that remote

``` bash
git push all master
```

Finally, you sure want to have all your refs up to date as well, so you can do:

``` bash
git fetch --all
```

to keep all your refs in sync with the all remote.

hint: you can do the last two operations in one command, with the following alias:

``` bash
git config alias.pushall "!pushall() { git push all $1 && git fetch --all ; }; pushall"
```

So I'm sure your tool does more than just that, but I thought I'd tell you about this, and I believe it'd be a good idea that you'd take advantage of that feature in your tool as well!

HTH

**Comment by earwig** [comment]
This tool's main purpose is to manage multiple git repos across your filesystem. I'm not sure how configuring multiple remotes within a single repository helps with this.

**Comment by Xaelias** [comment]
The tool just keeps track of multiple repos, and ensure they are all up to date. Not that a given repo is up to date among multiple source of truth. I'm with earwig here, I don't think this helps. But it's always good to know anyway.

**Comment by guyzmo** [comment]
ok, my bad, didn't get things right when I read the readme (to my defense, I'm currently under painkillers, so I can miss the obvious ^^).
