### ISSUE TITLE
"Silent" option?

### ISSUE THREAD

**Issue by parkr** [earwig/git-repo-updater#38]
Hey!

I wrote my own little custom updater some time ago but came across this project recently and strongly preferred it because it is used by more than 1 person and is open source, etc. Thanks for writing this tool!

I run this in a cron job, and its output is sent as mail to my user every time it runs. I'd love it if there were a "silent" mode such that only *failed* actions would be output. If the update was performed successfully, there would be no output.

What do you think?

**Comment by earwig** [comment]
You're right, I will implement this.
