### ISSUE TITLE
Homebrew Installation Requires Python@2

### ISSUE THREAD

**Issue by JustinJiaDev** [earwig/git-repo-updater#43]
According to the README,  looks like Python 3 should be supported. Maybe Python 2 requirement can dropped.

**Comment by earwig** [comment]
Yup, it's python-version-agnostic. I'll see about updating the brew package.

**Comment by JustinJiaDev** [comment]
According to [formula cookbook](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#check-for-dependencies), it looks like:

https://github.com/Homebrew/homebrew-core/blob/015f3f25a16f0a5ca74bdf7eb00f4990d6de39e2/Formula/gitup.rb#L15

just need to be changed from:

```
  depends_on "python@2"
```

to:

```ruby
  depends_on :python
```

But I didn't test it myself so I'm not 100% sure.

**Comment by earwig** [comment]
I believe you are correct; somehow this fell off my radar and I forgot to do it, even though it's a very easy change. For what it's worth, anyone is allowed to send PRs for homebrew (I'm not even the original author of that formula), so feel free to do it yourself after testing!
