### ISSUE TITLE
[feature request] Package Manager Install

### ISSUE THREAD

**Issue by smarbos** [earwig/git-repo-updater#46]
I think would be very usefull if there're was a way to perform a "npm install" after pulling changes from the remote.
I know not everybody uses npm, so I guess we can add support for yaml, for example, also, and perform a check of what package manager is being used, and call proper command.
I would like to implement this behaviour, I would like to know what do you think will be the better way to do this.

Thanks for your time, Damian.

**Comment by earwig** [comment]
This is not a bad idea, but I’d like to keep it general. There’s already an --exec flag, but it’s designed to run a command on every repo unconditionally. I think we can add an --exec-after flag that runs a command after updating, and only if there was an update to the checked-out branch.

**Comment by JedMeister** [comment]
@earwig - what about some sort of support for repo hook scripts? E.g. a flag which tells `git-repo-updater` to run a specific script (if found) within each repo after a successful pull? It could then be completely generic as far as `git-repo-updater` is concerned, but extremely specific for what the end user wants to do.

Having said that, don't [githooks](https://git-scm.com/docs/githooks) already cover both the explicit usecase mentioned here by @smarbos, plus many other possible general requests?

FWIW a quick google turned up [this gist](https://gist.github.com/sindresorhus/7996717) - which looks like it may be exactly like what you were after @smarbos?!

**Comment by earwig** [comment]
Indeed, a git hook sounds like a much better solution. I'm not opposed to adding --exec-after, but adding an option to run some script within each repo is just reimplementing git hooks, so users should take advantage of that functionality where possible.

**Comment by earwig** [comment]
Closing for now as we seem to have come to a conclusion here. Feel free to reopen if you see fit.
