### ISSUE TITLE
PyPI install?

### ISSUE THREAD

**Issue by slhck** [earwig/git-repo-updater#47]
Would it be possible to upload this project as `gitup` or `git-repo-updater` to PyPI so that we could simply install (and update) via `pip`?

Homebrew already provides a convenient update mechanism for macOS users, but it would be more general if it was available via PyPI.

PS: Thanks for this very useful script!

**Comment by earwig** [comment]
All set: https://pypi.org/project/gitup/

**Comment by slhck** [comment]
Awesome, thanks!
