### ISSUE TITLE
Prune and current directory doesn't work?

### ISSUE THREAD

**Issue by PovilasAtPoq** [earwig/git-repo-updater#50]
Hi,

i'm calling the tool with the command "python -m gitup . --prune" (the same result with "gitup . --prune"), but it doesn't perform prune command. No matter how many times I run it, the old branches are kept. Example message: Updating fix/XXXX-74/reviewsNotReturned: skipped: upstream does not exist.

Do I understand correctly, that --prune should remove those branches?

**Comment by earwig** [comment]
No, prune will never delete local branches. Its purpose is to delete remote tracking branches that were removed upstream. Deleting local branches sounds like a pretty scary operation.

By the way, it’s the same as git fetch --prune: https://git-scm.com/docs/git-fetch

**Comment by PovilasAtPoq** [comment]
Reread like three times about git pruning and i do not understand what that supposed to do. Sounds like it removes some kind of "link" between a local branch and remote. But why that would be needed I don't know :) However, for sure it's not supposed to delete local branches. So my bad for expecting it.

However, I have git-repo-updater maybe there's a tool which would automatically deal with those obsolete local branches? The goal is that any branch which was merged to remote and do not exist on remote should be deleted automatically.

**Comment by earwig** [comment]
Suppose your remote is named origin and there’s a branch called foo that gets deleted upstream. Prune will delete origin/foo, but it won’t delete foo. (Without prune, origin/foo would be kept even if deleted upstream.)

There’s probably a quick bash script you could throw together, though if you want to distinguish between branches deleted upstream and those that were never pushed, it might be a bit harder.

**Comment by PovilasAtPoq** [comment]
Thank you for your time, earwig! :) Not feeling like trying to write that script.

Also, thanks for this git-repo-updater! In the past I had a bat file, but it was only applicable for a specific branching model. Yours so much better! Have scheduled to run it every day.
