### ISSUE TITLE
[Suggestion] Add topics to the GitHub repo

### ISSUE THREAD

**Issue by chmac** [earwig/git-repo-updater#61]
I've just discovered totally by accident (trying to install gitup.co but getting this from brew). But I searched high and low for something to easily update several git repos at once. So it was a wonderful accident!

Would you be open to adding some topics to this GitHub repo? I think that would help others find it. A few suggestions would be:

- git
- multiple-repos
- monorepo

Can't think of any more useful topics right now.

**Comment by earwig** [comment]
Thanks for the suggestions! I've added a few more topics.
