### ISSUE TITLE
`pipes` got removed in py3.13

### ISSUE THREAD

**Issue by chenrui333** [earwig/git-repo-updater#69]
failed to run gitup after pip install gitup under py3.13

```
$ gitup --version
Traceback (most recent call last):
  File "/Users/rui/Downloads/brew/gitup/bin/gitup", line 5, in <module>
    from gitup.cli import run
  File "/Users/rui/Downloads/brew/gitup/lib/python3.13/site-packages/gitup/cli.py", line 18, in <module>
    from gitup.update import update_bookmarks, update_directories, run_command
  File "/Users/rui/Downloads/brew/gitup/lib/python3.13/site-packages/gitup/update.py", line 10, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```

relates to https://github.com/Homebrew/homebrew-core/pull/193501

**Comment by JedMeister** [comment]
In fairness, v3.13 was only released ~4 days ago & v3.12 is supported for another ~4 years...

Re the specifics of the issue importing `pipes` - see https://docs.python.org/3/library/pipes.html (emphasis is mine):

> Deprecated since version 3.11, **will be removed in version 3.13**

PS I'm not involved with this project, just a random passerby.

**Comment by chenrui333** [comment]
yeah, totally fair, I am just raising the awareness.

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/194097
